force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>ClassName</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Class__c/fields/Custom_Status__c.field-meta.xml
<CustomField>
    <fullName>Custom_Status__c</fullName>
    <label>Custom Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Close</fullName>
            </value>
            <value>
                <fullName>Reset</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Student Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/Classes.cls
public class Classes extends fflib_SObjectDomain {
    public Classes(List<Class__c> sObjectList) {
        super(sObjectList);
    }
    public class Constructor implements fflib_SObjectDomain.IConstructable {
        public fflib_SObjectDomain construct(List<SObject> sObjectList) {
            return new Classes(sObjectList);
        }
    }
    public override void onBeforeDelete() {
        List<Class__c> classList = ((new ClassesSelector()).classesWithFemaleStudents(existingRecords.keySet()));
        for(Class__c cl : classList) {
            if(cl.Students__r.size() > 1) {
                Class__c actualOldClass = (Class__c) existingRecords.get(cl.Id);
                actualOldClass.addError('Cannot delete Class having more than one Female Student!');
            }
        }
    }
    public override void onAfterUpdate(Map<Id,SObject> existingRecords) {
        List<Student__c> toBeDeletedStudentList = new List<Student__c>();
        Set<Id> resetStatusClassIdSet = new Set<Id>();
        for(Class__c cl : (List<Class__c>) Records) {
            Class__c oldClass = (Class__c) existingRecords.get(cl.Id);
            if(cl.Custom_Status__c != oldClass.Custom_Status__c && cl.Custom_Status__c == 'Reset') {
                resetStatusClassIdSet.add(cl.Id);
            }
        }
        toBeDeletedStudentList = ((new StudentsSelector()).getStudentsOfClasses(resetStatusClassIdSet));
        if(toBeDeletedStudentList != null && !toBeDeletedStudentList.isEmpty()) {
            delete toBeDeletedStudentList;
        }
    }
}