force-app/main/default/objects/Teach__c/Teach__c.object-meta.xml
<CustomObject>
    <label>Teach</label>
    <nameField>
        <displayFormat>T-{000}</displayFormat>
        <label>TeachID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Teachs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Teach__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hindi</fullName>
            </value>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>Maths</fullName>
            </value>
            <value>
                <fullName>Science</fullName>
            </value>
            <value>
                <fullName>Social Science</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Teachs.cls
public class Teachs extends fflib_SObjectDomain {
    public Teachs(List<Teach__c> sObjectList) {
        super(sObjectList);
    }
    public class Constructor implements fflib_SObjectDomain.IConstructable {
        public fflib_SObjectDomain construct(List<SObject> sObjectList) {
            return new Teachs(sObjectList);
        }
    }
    public override void onBeforeUpdate(Map<Id,SObject> existingRecords) {
        for(Teach__c tch : (List<Teach__c>) Records) {
            if(tch.Subject__c.contains('Hindi')) {
        		tch.Subject__c.addError('Cannot add Teacher teaching Hindi');
            }
        }
    }
    public override void onBeforeInsert() {
        for(Teach__c tch : (List<Teach__c>) Records) {
            if(tch.Subject__c.contains('Hindi')) {
        		tch.Subject__c.addError('Cannot add Teacher teaching Hindi');
            }
        }
    }
}